//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public int cod_horario { get; set; }
        public Nullable<int> cod_periodo { get; set; }
        public Nullable<int> cod_dias { get; set; }
        public string fecha_ini { get; set; }
        public int cod_asig { get; set; }
        public int cod_aula { get; set; }
        public int cod_grupo { get; set; }
        public string inss { get; set; }
        public int cod_ano { get; set; }
    
        public virtual aula aula { get; set; }
        public virtual dia dia { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual pensum pensum { get; set; }
        public virtual periodo periodo { get; set; }
        public virtual profesore profesore { get; set; }
    }
}
