//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class horariogeneracion
    {
        public int id { get; set; }
        public string cod_carrera { get; set; }
        public string tipo_ciclo { get; set; }
        public string fecha_ini { get; set; }
        public string cod_dpto { get; set; }
        public string semestr { get; set; }
        public string año_estudio { get; set; }
        public string profesor { get; set; }
        public string cod_aula { get; set; }
        public string cod_grupo { get; set; }
        public string cod_periodo { get; set; }
    }
}
