//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class pensum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pensum()
        {
            this.grupoes = new HashSet<grupo>();
            this.horarios = new HashSet<horario>();
            this.inportarcions = new HashSet<inportarcion>();
        }
    
        public int cod_asig { get; set; }
        public int N_credito { get; set; }
        public int ciclo { get; set; }
        public string anio_est { get; set; }
        public string prerrequisito1 { get; set; }
        public string prerrequisito2 { get; set; }
        public int cod_plan { get; set; }
        public int cod_materia { get; set; }
        public int total_horas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo> grupoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario> horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inportarcion> inportarcions { get; set; }
        public virtual materia materia { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
